### ISSUE TITLE
大佬，有没有使用文档？

### ISSUE THREAD

**Issue by losper** [HATTER-LONG/AUTestTools#3]
根据大佬的描述，貌似是一个自动分析CPP源码，然后生成测试代码，自动测试代码逻辑，覆盖所有分支？
请问有没有使用文档？

**Comment by HATTER-LONG** [comment]
并没有达到你说的这种功能 😭
当前仅仅实现到识别 CPP 调用关系这部分，可以生成些 MOCK 用的空函数，如果你想了解如何利用 libclang 分析可以看看 DOC 下的文档，其他的就不要浪费时间了，最近的重心并不在这个上。

**Comment by losper** [comment]
谢谢大佬，你的文档对我来说帮助也很大。:smile:
